---
- name: Configure KeePass CVE-2023-32784 on DMZ Jump
  hosts: dmz:&jump
  gather_facts: false
  # strategy: free

  tasks:
    - name: Get DefaultUserName from Registry
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultUserName
      register: default_username

    - name: Debug DefaultUserName
      debug:
        var: default_username

    - name: Get DefaultDomainName from Registry
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultDomainName
      register: default_domain

    - name: Debug DefaultDomainName
      debug:
        var: default_domain

    - name: Set domain\username variable
      set_fact:
        domain_username: "{{ default_domain['value'] }}\\{{ default_username['value'] }}"

    - name: Debug domain\username variable
      debug:
        msg: "Target User: {{ domain_username }}"

    - name: Remove autologon credentials
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "{{ item }}"
        state: absent
      with_items:
        - "DefaultUserName"
        - "DefaultPassword"
        - "DefaultDomainName"
        - "AutoAdminLogon"

    - name: Delete the scheduled task
      win_scheduled_task:
        name: "StartKeePass"
        state: absent
