---
- name: Enable SSH Password Authentication
  hosts: "dmz:supervision:&linux"
  gather_facts: false
  become: yes

  tasks:
    - name: Enable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Permit Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Remove all files from /etc/ssh/sshd_config.d/
      file:
        path: /etc/ssh/sshd_config.d/
        state: absent

    - name: Recreate the /etc/ssh/sshd_config.d/ directory
      file:
        path: /etc/ssh/sshd_config.d/
        state: directory
        mode: '0755'
