---
- name: Setup Enterprise File Server
  hosts: enterprise:&fs
  gather_facts: false

  tasks:
    - name: Split hostname and extract the team part
      set_fact:
        team_name: "{{ inventory_hostname.split('_')[0] }}"

    - name: Debug the extracted team name
      debug:
        msg: "The team name extracted is {{ team_name }} on {{ inventory_hostname }}"

    - name: Get environment ID
      set_fact:
        environment_id: "{{ lookup('vars', team_name ~ '_environment_id') }}"

    - name: Debug environment ID
      debug:
        msg: "Environment ID for Team {{ team_name }} is {{ environment_id }}"

    - name: Copy initial_setup_enterprise_file_server.ps1 to Enterprise File Server
      win_copy:
        src: ./scripts/initial_setup_enterprise_file_server.ps1
        dest: C:\Windows\Temp\initial_setup_enterprise_file_server.ps1

    - name: Copy utils.psm1 to Enterprise File Server
      win_copy:
        src: ./scripts/utils.psm1
        dest: C:\Windows\Temp\utils.psm1

    - name: Copy config.json to Enterprise File Server
      win_copy:
        src: "./configs/config_{{ environment_id }}.json"
        dest: C:\Windows\Temp\config.json

    - name: Copy inventory.json to Enterprise File Server
      win_copy:
        src: ./inventory_{{ team_name }}.json
        dest: C:\Windows\Temp\inventory.json

    - name: Run Setup Script (First Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass \
        -File C:\Windows\Temp\initial_setup_enterprise_file_server.ps1 \
        C:\Windows\Temp\config.json \
        C:\Windows\Temp\inventory.json
      register: setup_output
    - debug:
        msg:
          - "=== STDOUT ==="
          - "{{ setup_output.stdout_lines | default('No stdout output') }}"
          - "=== STDERR ==="
          - "{{ setup_output.stderr_lines | default('No stderr output') }}"

    - name: Reboot
      win_reboot:

    - name: Run Setup Script (Second Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass \
        -File C:\Windows\Temp\initial_setup_enterprise_file_server.ps1 \
        C:\Windows\Temp\config.json \
        C:\Windows\Temp\inventory.json
      register: setup_output
    - debug:
        msg:
          - "=== STDOUT ==="
          - "{{ setup_output.stdout_lines | default('No stdout output') }}"
          - "=== STDERR ==="
          - "{{ setup_output.stderr_lines | default('No stderr output') }}"

    - name: Reboot
      win_reboot:

    - name: Run Setup Script (Third Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass \
        -File C:\Windows\Temp\initial_setup_enterprise_file_server.ps1 \
        C:\Windows\Temp\config.json \
        C:\Windows\Temp\inventory.json
      register: setup_output
    - debug:
        msg:
          - "=== STDOUT ==="
          - "{{ setup_output.stdout_lines | default('No stdout output') }}"
          - "=== STDERR ==="
          - "{{ setup_output.stderr_lines | default('No stderr output') }}"

    - name: Reboot
      win_reboot:

    - name: Run Setup Script (Fourth Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass \
        -File C:\Windows\Temp\initial_setup_enterprise_file_server.ps1 \
        C:\Windows\Temp\config.json \
        C:\Windows\Temp\inventory.json
      register: setup_output
    - debug:
        msg:
          - "=== STDOUT ==="
          - "{{ setup_output.stdout_lines | default('No stdout output') }}"
          - "=== STDERR ==="
          - "{{ setup_output.stderr_lines | default('No stderr output') }}"

    - name: Remove initial_setup_enterprise_file_server.ps1 after execution
      win_file:
        path: C:\Windows\Temp\initial_setup_enterprise_file_server.ps1
        state: absent

    - name: Remove utils.psm1 after execution
      win_file:
        path: C:\Windows\Temp\utils.psm1
        state: absent

    - name: Remove config.json after execution
      win_file:
        path: C:\Windows\Temp\config.json
        state: absent

    - name: Remove inventory.json after execution
      win_file:
        path: C:\Windows\Temp\inventory.json
        state: absent

    - name: Remove StealthCupSetup.log after execution
      win_file:
        path: C:\Windows\Temp\StealthCupSetup.log
        state: absent

    - name: Copy the website to the Enterprise File Server
      win_copy:
        src: ./files/website_{{ environment_id }}.zip
        dest: C:\inetpub\wwwroot\website.zip

    - name: Extract the website
      win_unzip:
        src: C:\inetpub\wwwroot\website.zip
        dest: C:\inetpub\wwwroot\

    - name: Remove website.zip after extracting
      win_file:
        path: C:\inetpub\wwwroot\website.zip
        state: absent

    - name: Copy the documentation to the Enterprise File Server
      win_copy:
        src: ./files/IT-Documentation.pdf
        dest: C:\Fileshares\IT\IT-Documentation.pdf

    - name: Copy the email exports to the Enterprise File Server
      win_copy:
        src: ../templates/email/email_exports.zip
        dest: C:\Fileshares\IT\email_exports.zip
