---
- name: Update Local Account Passwords Linux
  hosts: "dmz:supervision:&linux"
  gather_facts: false
  become: yes

  tasks:
    - name: Split hostname and extract the team part
      set_fact:
        team_name: "{{ inventory_hostname.split('_')[0] }}"

    - name: Debug the extracted team name
      debug:
        msg: "The team name extracted is {{ team_name }} on {{ inventory_hostname }}"

    - name: Get environment ID
      set_fact:
        environment_id: "{{ lookup('vars', team_name ~ '_environment_id') }}"

    - name: Debug environment ID
      debug:
        msg: "Environment ID for Team {{ team_name }} is {{ environment_id }}"

    - name: Set config file
      set_fact:
        configuration_file: "./configs/config_{{ environment_id }}.json"

    - name: Load configuration JSON from local machine
      set_fact:
        configuration_json: "{{ lookup('file', configuration_file) | from_json }}"

    - name: Extract machine name from inventory_hostname
      set_fact:
        machine_name: "{{ inventory_hostname.split('_', 1)[1] if '_' in inventory_hostname else inventory_hostname }}"

    - name: Get workstation configuration
      set_fact:
        workstation_configuration: >-
          {{ configuration_json['LinuxHosts'] | selectattr('HostID', 'equalto', machine_name) | list | first | default({}) }}

    - name: Debug workstation configuration
      debug:
        msg: "{{ workstation_configuration }}"

    - name: Update users !supervision_scada (without sudo)
      user:
        name: "{{ item['Username'] }}"
        password: "{{ item['Password'] | password_hash('sha512') }}"
        create_home: yes
      loop: "{{ workstation_configuration['LocalAccounts'] }}"
      when: machine_name != "supervision_scada"

    - name: Update users supervision_scada (with sudo)
      user:
        name: "{{ item['Username'] }}"
        password: "{{ item['Password'] | password_hash('sha512') }}"
        groups: sudo
        append: yes
        create_home: yes
      loop: "{{ workstation_configuration['LocalAccounts'] }}"
      when: machine_name == "supervision_scada"
