- name: Update Grafana Admin Password
  hosts: "dmz:&historian"
  gather_facts: false
  become: true

  tasks:
  - name: Split hostname and extract the team part
    set_fact:
      team_name: "{{ inventory_hostname.split('_')[0] }}"

  - name: Debug the extracted team name
    debug:
      msg: "The team name extracted is {{ team_name }} on {{ inventory_hostname }}"

  - name: Get environment ID
    set_fact:
      environment_id: "{{ lookup('vars', team_name ~ '_environment_id') }}"

  - name: Debug environment ID
    debug:
      msg: "Environment ID for Team {{ team_name }} is {{ environment_id }}"

  - name: Set config file
    set_fact:
      configuration_file: "./configs/config_{{ environment_id }}.json"

  - name: Load configuration JSON from local machine
    set_fact:
      configuration_json: "{{ lookup('file', configuration_file) | from_json }}"

  - name: Get grafana configuration
    set_fact:
      grafana_configuration: >-
        {{ configuration_json['Software'] | selectattr('SoftwareID', 'equalto', 'grafana') | list | first | default({}) }}

  - name: Debug grafana configuration
    debug:
      msg: "{{ grafana_configuration }}"

  - name: Extract grafana credentials
    set_fact:
      grafana_username: "{{ grafana_configuration['Username'] | default({}) }}"
      grafana_password: "{{ grafana_configuration['Password'] | default({}) }}"
      grafana_hash: "{{ grafana_configuration['Hash'] | default({}) }}"
      grafana_salt: "{{ grafana_configuration['Salt'] | default({}) }}"

  - name: Update apt package list
    apt:
      update_cache: yes
    become: true

  - name: Install SQLite3
    apt:
      name: sqlite3
      state: present

  - name: Update the Grafana user password in SQLite using Bash
    ansible.builtin.shell: |
      sqlite3 /var/lib/grafana/grafana.db "UPDATE user SET password='{{ grafana_hash }}', salt='{{ grafana_salt }}', rands=NULL WHERE login='{{ grafana_username }}';"
    register: update_result

  - name: Debug update result
    debug:
      var: update_result

  - name: Restart Grafana service
    ansible.builtin.service:
      name: grafana-server
      state: restarted
