---
- name: Update Scada ADmin Password
  hosts: supervision:&scada
  gather_facts: false
  become: true

  vars:
    db_username: "root"
    db_password: "root"

  tasks:
    - name: Split hostname and extract the team part
      set_fact:
        team_name: "{{ inventory_hostname.split('_')[0] }}"

    - name: Debug the extracted team name
      debug:
        msg: "The team name extracted is {{ team_name }} on {{ inventory_hostname }}"

    - name: Get environment ID
      set_fact:
        environment_id: "{{ lookup('vars', team_name ~ '_environment_id') }}"

    - name: Debug environment ID
      debug:
        msg: "Environment ID for Team {{ team_name }} is {{ environment_id }}"

    - name: Set config file
      set_fact:
        configuration_file: "./configs/config_{{ environment_id }}.json"

    - name: Load configuration JSON from local machine
      set_fact:
        configuration_json: "{{ lookup('file', configuration_file) | from_json }}"

    - name: Get scada configuration
      set_fact:
        scada_configuration: >-
          {{ configuration_json['Software'] | selectattr('SoftwareID', 'equalto', 'scada') | list | first | default({}) }}

    - name: Debug Scada configuration
      debug:
        msg: "{{ scada_configuration }}"

    - name: Extract Scada Credentials
      set_fact:
        scada_username: "{{ scada_configuration['Username'] | default({}) }}"
        scada_password: "{{ scada_configuration['Password'] | default({}) }}"
        scada_hash: "{{ scada_configuration['Hash'] | default({}) }}"
        
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present

    - name: Update password hash for admin user in scadalts database
      shell: |
        mysql -u {{ db_username }} --password={{ db_password }} -h 127.0.0.1 -P 3306 -e \
        "USE scadalts; UPDATE users SET password = '{{ scada_hash }}' WHERE username = '{{ scada_username }}';"
