---
- name: Update KRBTGT Account Password
  hosts: dc
  gather_facts: false

  tasks:
    - name: Copy KRBTGT reset script to Domain Controller
      win_copy:
        src: ./scripts/New-KrbtgtKeys.ps1
        dest: C:\Windows\Temp\New-KrbtgtKeys.ps1

    - name: Run KRBTGT reset script (First Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Temp\New-KrbtgtKeys.ps1

    - name: Run KRBTGT reset script (Second Execution)
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Temp\New-KrbtgtKeys.ps1

    - name: Remove KRBTGT reset script after execution
      win_file:
        path: C:\Windows\Temp\New-KrbtgtKeys.ps1
        state: absent
