---
- name: Windows | Set Win Path (x86)
  set_fact:
    wazuh_agent_win_path: "{{ wazuh_winagent_config.install_dir_x86 }}"
    wazuh_agent_win_auth_path: "{{ wazuh_winagent_config.auth_path_x86 }}"

- name: Windows | Installing agent configuration (ossec.conf)
  template: # noqa 208
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: "{{ wazuh_agent_win_path }}ossec.conf"
  notify: Windows | Restart Wazuh Agent
  tags:
    - config

- name: Windows | Installing local_internal_options.conf
  template:
    src: var-ossec-etc-local-internal-options.conf.j2
    dest: "{{ wazuh_agent_win_path }}local_internal_options.conf"
  notify: Windows | Restart Wazuh Agent
  tags:
    - config
