- name: Check if kerbrute is already downloaded
  stat:
    path: /usr/local/bin/kerbrute
  register: kerbrute
- name: Setup kerbrute
  shell: | 
    wget https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
    chmod +x kerbrute_linux_amd64
    sudo mv kerbrute_linux_amd64 /usr/local/bin/kerbrute
  when:
    - not kerbrute.stat.exists
- name: Install impacket
  apt:
    name: impacket-scripts  # Replace with the package you want to install
    state: present           # Ensures the package is installed
    update_cache: yes        # Update the apt cache before installing
  become: yes
- name: Install certipy
  apt:
    name: certipy-ad
    state: present
  become: yes
- name: Install coercer
  apt:
    name: coercer
    state: present
  become: yes
- name: Install NetExec
  apt:
    name: netexec
    state: present
  become: yes
- name: Check if Lists are already copied
  stat:
    path: passwords.txt
  register: lists
- name: Copy Lists
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
      - { src: 'passwords.txt', dest: 'passwords.txt'}
      - { src: 'usernames.txt', dest: 'usernames.txt'}
  when:
    - not lists.stat.exists

# run with ansible hacker -m include_role -a 'name=kali/setup' -u kali

