---
collections:
  - name: grafana.grafana
    version: 5.6.0

roles:
  - src: https://github.com/rossmcdonald/influxdb.git
    scm: git
    version: master
    name: influxdb

  - src: https://github.com/dj-wasabi/ansible-telegraf.git
    scm: git
    version: master
    name: telegraf

