nodes:
  # Indexer server nodes
  indexer:
    - name: node-1
      ip: 127.0.0.1

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:

  # Dashboard node
  dashboard:
